services:
  # Главная, seed 1
  cassandra1:
    build: cassandra:5.0.5
    environment:
      - CASSANDRA_SEEDS=192.168.1.200,192.168.1.201   # список seed нод
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.200
      - MAX_HEAP_SIZE=512M                            # можете увеличить если нужно
      - HEAP_NEWSIZE=100M
    networks:
      cassandra_net:
        ipv4_address: 192.168.1.200
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local;' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Seed 2
  cassandra2:
    image: cassandra:5.0.5
    environment:
      - CASSANDRA_SEEDS=192.168.1.200,192.168.1.201
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.201
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    depends_on:
      cassandra1:
        condition: service_healthy
    networks:
      cassandra_net:
        ipv4_address: 192.168.1.201
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local;' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Простая нода, подтягивается к первым 2
  cassandra3:
    image: cassandra:5.0.5
    environment:
      - CASSANDRA_SEEDS=192.168.1.200,192.168.1.201
      - CASSANDRA_BROADCAST_ADDRESS=192.168.1.202
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    depends_on:
      cassandra1:
        condition: service_healthy
    networks:
      cassandra_net:
        ipv4_address: 192.168.1.202
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local;' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  cassandra_net:
    driver: ipvlan
    driver_opts:
      parent: eth0  # замените на ваш интерфейс если отличается
    ipam:
      config:
        - subnet: 192.168.1.0/24  # ваша подсеть